spring:
  application:
    name: commerce-coupon-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 3600

# 🔧 JWT 설정을 spring 블록 외부로 이동
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationThatShouldBeLongEnoughToBeSecure}
  token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800
  header: Authorization
  token-prefix: "Bearer "
  issuer: commerce-coupon-be

# 🔧 Springdoc도 외부로 이동
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC

logging:
  level:
    com.commercecoupon.commercecouponbe: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"